<?php

namespace App\Services\V1\Chat\Session;

use App\Models\ChatSession;
use App\Repositories\V1\Contracts\ChatRepositoryInterface;
use App\Services\V1\DTOs\SendChatMessageDTO;

/**
 * Service for resolving or creating chat sessions.
 *
 * Follows Single Responsibility Principle (SRP): Only responsible for
 * finding existing sessions or creating new ones.
 */
class SessionResolver
{
    public function __construct(
        private readonly ChatRepositoryInterface $chatRepository
    ) {}

    /**
     * Get or create chat session.
     *
     * @param SendChatMessageDTO $dto
     * @return ChatSession
     */
    public function resolve(SendChatMessageDTO $dto): ChatSession
    {
        if ($dto->sessionId) {
            $session = $this->chatRepository->findSessionByUuid($dto->sessionId, $dto->companyId);
            if ($session) {
                return $session;
            }
        }

        // Create new session (uuid is auto-generated by model boot method)
        return $this->createSession($dto);
    }

    private function createSession(SendChatMessageDTO $dto): ChatSession
    {
        return $this->chatRepository->createSession([
            'company_id' => $dto->companyId,
            'user_metadata' => $dto->userMetadata,
            'created_at' => now(),
        ]);
    }
}
